/**
 * Test Executor - Executes planned test scenarios
 *
 * The executor is responsible for running test scenarios generated by the planner.
 * It's a pure execution engine that doesn't make decisions - it just follows the plan.
 *
 * Main implementation: PlaywrightExecutor - uses Playwright to execute steps
 */

import {
  PlannedScenario,
  PlannedStep,
  PlannedAssertion,
  ScenarioResult,
  StepResult,
  AssertionResult,
  Artifact,
  ConsoleLog,
  ArtifactType,
  StepAction,
  AssertionType
} from './types';
import { chromium, type Browser, type BrowserContext, type Page, type ConsoleMessage } from 'playwright';

/**
 * Actual value from step execution
 * Can be primitive types, null, or undefined
 */
type StepActualValue = string | number | boolean | null | undefined;
import * as fs from 'fs';
import * as path from 'path';
import { BrowserPool } from '../browser/browser-pool';

// =====================================================
// EXECUTOR INTERFACE
// =====================================================

/**
 * Interface for test executors
 */
export interface ITestExecutor {
  /**
   * Execute a test scenario
   * @param scenario - Scenario to execute
   * @param page - Playwright page instance (optional, executor creates own if not provided)
   * @returns Promise<ScenarioResult> - Execution result
   */
  execute(scenario: PlannedScenario, page?: Page): Promise<ScenarioResult>;
}

// =====================================================
// EXECUTOR CONFIGURATION
// =====================================================

/**
 * Configuration for Playwright executor
 */
export interface PlaywrightExecutorConfig {
  /** Output directory for artifacts */
  outputDir?: string;
  /** Whether to take screenshots */
  enableScreenshots?: boolean;
  /** Whether to collect console logs */
  enableConsoleLogs?: boolean;
  /** Whether to collect network logs */
  enableNetworkLogs?: boolean;
  /** Base URL for relative navigation */
  baseUrl?: string;
  /** Default timeout for operations */
  defaultTimeout?: number;
  /** Maximum retry attempts for failed steps */
  maxRetries?: number;
  /** Retry delay in milliseconds */
  retryDelay?: number;
  /** Browser launch options */
  launchOptions?: {
    headless?: boolean;
    slowMo?: number;
    devtools?: boolean;
  };
  /** Optional BrowserPool for shared browser instances */
  browserPool?: BrowserPool;
}

// =====================================================
// PLAYWRIGHT EXECUTOR
// =====================================================

/**
 * Playwright-based test executor
 * Executes planned scenarios using Playwright browser automation
 */
export class PlaywrightExecutor implements ITestExecutor {
  private config: Required<PlaywrightExecutorConfig>;
  private browser?: Browser;
  private context?: BrowserContext;
  private ownPage?: Page;
  private artifacts: Artifact[] = [];
  private browserPool?: BrowserPool;
  private pooledPage?: Page;

  constructor(config: PlaywrightExecutorConfig = {}) {
    this.config = {
      outputDir: config.outputDir || './artifacts',
      enableScreenshots: config.enableScreenshots !== false,
      enableConsoleLogs: config.enableConsoleLogs !== false,
      enableNetworkLogs: config.enableNetworkLogs !== false,
      baseUrl: config.baseUrl || '',
      defaultTimeout: config.defaultTimeout || 30000,
      maxRetries: config.maxRetries || 3,
      retryDelay: config.retryDelay || 1000,
      launchOptions: {
        headless: config.launchOptions?.headless !== false,
        slowMo: config.launchOptions?.slowMo || 0,
        devtools: config.launchOptions?.devtools || false,
      },
      browserPool: config.browserPool,
    };

    // Store browser pool reference
    this.browserPool = config.browserPool;

    // Ensure output directory exists
    if (!fs.existsSync(this.config.outputDir)) {
      fs.mkdirSync(this.config.outputDir, { recursive: true });
    }
  }

  /**
   * Execute a test scenario
   */
  async execute(scenario: PlannedScenario, page?: Page): Promise<ScenarioResult> {
    const startTime = Date.now();
    const stepResults: StepResult[] = [];
    const assertionResults: AssertionResult[] = [];
    const artifacts: Artifact[] = [];
    const consoleLogs: ConsoleLog[] = [];

    try {
      // Use provided page or create own
      const useOwnPage = !page;
      let executionPage = page;

      if (useOwnPage) {
        await this.initialize();
        executionPage = this.ownPage!;
        this.setupConsoleLogging(executionPage, consoleLogs);
      }

      // Set viewport if specified
      if (scenario.viewport && executionPage) {
        await executionPage.setViewportSize(scenario.viewport);
      }

      // Handle authentication if specified
      if (scenario.auth && executionPage) {
        await this.handleAuthentication(scenario, executionPage);
      }

      // Execute steps
      for (const step of scenario.steps) {
        const stepResult = await this.executeStep(step, executionPage!, consoleLogs, artifacts);
        stepResults.push(stepResult);

        // Stop if critical step failed
        if (!stepResult.passed && stepResult.step.critical !== false) {
          break;
        }
      }

      // Execute assertions
      for (const assertion of scenario.assertions) {
        const assertionResult = await this.executeAssertion(assertion, executionPage!, consoleLogs, artifacts);
        assertionResults.push(assertionResult);
      }

      // Take final screenshot if enabled
      if (this.config.enableScreenshots && executionPage) {
        const screenshotPath = await this.takeScreenshot(executionPage, 'final');
        if (screenshotPath) {
          artifacts.push({
            type: 'screenshot',
            path: screenshotPath,
            timestamp: new Date().toISOString(),
          });
        }
      }

      // Collect console logs as artifact
      if (this.config.enableConsoleLogs && consoleLogs.length > 0) {
        const logPath = await this.saveConsoleLogs(consoleLogs, scenario.id);
        if (logPath) {
          artifacts.push({
            type: 'console-log',
            path: logPath,
            timestamp: new Date().toISOString(),
          });
        }
      }

      // Cleanup if we created our own page
      if (useOwnPage) {
        await this.cleanup();
      }

      // Determine overall pass/fail
      const allStepsPassed = stepResults.every(r => r.passed);
      const allAssertionsPassed = assertionResults.every(r => r.passed);
      const passed = allStepsPassed && allAssertionsPassed;

      const duration = Date.now() - startTime;

      return {
        scenarioId: scenario.id,
        scenarioName: scenario.name,
        url: scenario.url,
        passed,
        stepResults,
        assertionResults,
        artifacts,
        duration,
        timestamp: new Date().toISOString(),
      };
    } catch (error) {
      // Cleanup on error
      await this.cleanup();

      return {
        scenarioId: scenario.id,
        scenarioName: scenario.name,
        url: scenario.url,
        passed: false,
        stepResults,
        assertionResults,
        artifacts,
        duration: Date.now() - startTime,
        timestamp: new Date().toISOString(),
        error: error.message,
      };
    }
  }

  /**
   * Initialize browser and page
   */
  private async initialize(): Promise<void> {
    if (this.browserPool) {
      // Use BrowserPool for page management
      this.pooledPage = await this.browserPool.acquirePage();
      this.ownPage = this.pooledPage;
    } else {
      // Launch own browser (backward compatibility)
      this.browser = await chromium.launch(this.config.launchOptions);
      this.context = await this.browser.newContext();
      this.ownPage = await this.context.newPage();
    }
  }

  /**
   * Setup console logging
   */
  private setupConsoleLogging(page: Page, consoleLogs: ConsoleLog[]): void {
    if (!this.config.enableConsoleLogs) return;

    page.on('console', (msg: ConsoleMessage) => {
      consoleLogs.push({
        level: msg.type(),
        message: msg.text(),
        timestamp: Date.now(),
      });
    });
  }

  /**
   * Handle authentication
   */
  private async handleAuthentication(scenario: PlannedScenario, page: Page): Promise<void> {
    if (!scenario.auth) return;

    const { loginUrl, username, password, verifySelector } = scenario.auth;

    // Navigate to login page
    await page.goto(loginUrl, { timeout: this.config.defaultTimeout });

    // Fill username and password (assuming standard form)
    // This is simplified - real implementation would need more robust selector handling
    try {
      const usernameInput = await page.waitForSelector('input[type="text"], input[name="username"], input[name="email"]', { timeout: 5000 });
      await usernameInput.fill(username);

      const passwordInput = await page.waitForSelector('input[type="password"]', { timeout: 5000 });
      await passwordInput.fill(password);

      // Submit form
      const submitButton = await page.waitForSelector('button[type="submit"], input[type="submit"]', { timeout: 5000 });
      await submitButton.click();

      // Wait for login to complete
      if (verifySelector) {
        await page.waitForSelector(verifySelector, { timeout: this.config.defaultTimeout });
      } else {
        await page.waitForLoadState('networkidle', { timeout: this.config.defaultTimeout });
      }
    } catch (error) {
      throw new Error(`Authentication failed: ${error.message}`);
    }
  }

  /**
   * Execute a single step
   */
  private async executeStep(
    step: PlannedStep,
    page: Page,
    consoleLogs: ConsoleLog[],
    artifacts: Artifact[]
  ): Promise<StepResult> {
    const startTime = Date.now();
    let passed = false;
    let actual: StepActualValue;
    let error: string | undefined;
    let screenshot: string | undefined;

    try {
      await this.executeStepAction(step, page);
      passed = true;
      actual = 'Step executed successfully';

      // Take screenshot if requested
      if (step.screenshot && this.config.enableScreenshots) {
        screenshot = await this.takeScreenshot(page, `step-${step.id}`);
        if (screenshot) {
          artifacts.push({
            type: 'screenshot',
            path: screenshot,
            timestamp: new Date().toISOString(),
          });
        }
      }

      // Wait if specified
      if (step.waitAfter) {
        await page.waitForTimeout(step.waitAfter);
      }
    } catch (stepError) {
      error = stepError.message;
      passed = false;

      // Take screenshot on failure if enabled
      if (this.config.enableScreenshots) {
        screenshot = await this.takeScreenshot(page, `step-${step.id}-error`);
        if (screenshot) {
          artifacts.push({
            type: 'screenshot',
            path: screenshot,
            timestamp: new Date().toISOString(),
          });
        }
      }
    }

    return {
      step,
      passed,
      actual,
      error,
      screenshot,
      consoleLogs: [...consoleLogs], // Snapshot of logs at this point
      duration: Date.now() - startTime,
      timestamp: new Date().toISOString(),
    };
  }

  /**
   * Execute a step action
   */
  private async executeStepAction(step: PlannedStep, page: Page): Promise<void> {
    const timeout = this.config.defaultTimeout;

    switch (step.action) {
      case 'navigate':
      case 'goto':
        const url = step.value && step.value.startsWith('http') ? step.value : this.config.baseUrl + step.value;
        await page.goto(url, { timeout });
        break;

      case 'click':
        if (!step.selector) throw new Error('Click action requires selector');
        await page.waitForSelector(step.selector, { timeout });
        await page.click(step.selector, { timeout });
        break;

      case 'type':
        if (!step.selector) throw new Error('Type action requires selector');
        await page.waitForSelector(step.selector, { timeout });
        await page.fill(step.selector, step.value || '', { timeout });
        break;

      case 'wait':
        const waitTime = step.value ? parseInt(step.value) : 1000;
        await page.waitForTimeout(waitTime);
        break;

      case 'scroll':
        await page.evaluate(() => {
          window.scrollTo(0, document.body.scrollHeight);
        });
        break;

      case 'hover':
        if (!step.selector) throw new Error('Hover action requires selector');
        await page.waitForSelector(step.selector, { timeout });
        await page.hover(step.selector, { timeout });
        break;

      case 'select':
        if (!step.selector) throw new Error('Select action requires selector');
        await page.waitForSelector(step.selector, { timeout });
        await page.selectOption(step.selector, step.value || '', { timeout });
        break;

      case 'submit':
        if (!step.selector) throw new Error('Submit action requires selector');
        await page.waitForSelector(step.selector, { timeout });
        await page.press(step.selector, 'Enter', { timeout });
        break;

      case 'screenshot':
        // Screenshot action is handled by the caller
        break;

      case 'assert':
        // Assert action is handled by assertions
        break;

      case 'javascript':
        if (step.value) {
          await page.evaluate(step.value);
        }
        break;

      default:
        throw new Error(`Unknown action: ${step.action}`);
    }
  }

  /**
   * Execute an assertion
   */
  private async executeAssertion(
    assertion: PlannedAssertion,
    page: Page,
    consoleLogs: ConsoleLog[],
    artifacts: Artifact[]
  ): Promise<AssertionResult> {
    let passed = false;
    let actual: StepActualValue;
    let error: string | undefined;
    let screenshot: string | undefined;

    try {
      const result = await this.evaluateAssertion(assertion, page, consoleLogs);
      passed = result.passed;
      actual = result.actual;

      // Take screenshot on failure if enabled
      if (!passed && this.config.enableScreenshots) {
        screenshot = await this.takeScreenshot(page, `assertion-${assertion.type}-error`);
        if (screenshot) {
          artifacts.push({
            type: 'screenshot',
            path: screenshot,
            timestamp: new Date().toISOString(),
          });
        }
      }
    } catch (assertionError) {
      error = assertionError.message;
      passed = false;
    }

    return {
      assertion,
      passed,
      actual,
      error,
      screenshot,
    };
  }

  /**
   * Evaluate an assertion
   */
  private async evaluateAssertion(
    assertion: PlannedAssertion,
    page: Page,
    consoleLogs: ConsoleLog[]
  ): Promise<{ passed: boolean; actual: StepActualValue }> {
    switch (assertion.type) {
      case 'element-exists':
        if (!assertion.selector) throw new Error('element-exists requires selector');
        const element = await page.$(assertion.selector);
        return {
          passed: element !== null,
          actual: element !== null,
        };

      case 'element-visible':
        if (!assertion.selector) throw new Error('element-visible requires selector');
        const isVisible = await page.isVisible(assertion.selector);
        return { passed: isVisible, actual: isVisible };

      case 'element-count':
        if (!assertion.selector) throw new Error('element-count requires selector');
        const count = await page.locator(assertion.selector).count();
        return { passed: count === assertion.expected, actual: count };

      case 'text-contains':
        if (!assertion.selector) throw new Error('text-contains requires selector');
        const text = await page.textContent(assertion.selector);
        const expectedStr = typeof assertion.expected === 'string' ? assertion.expected : String(assertion.expected);
        const contains = text ? text.includes(expectedStr) : false;
        return { passed: contains, actual: text };

      case 'text-equals':
        if (!assertion.selector) throw new Error('text-equals requires selector');
        const textContent = await page.textContent(assertion.selector);
        const equals = textContent === assertion.expected;
        return { passed: equals, actual: textContent };

      case 'attribute-equals':
        if (!assertion.selector || !assertion.attribute) throw new Error('attribute-equals requires selector and attribute');
        const attrValue = await page.getAttribute(assertion.selector, assertion.attribute);
        return { passed: attrValue === assertion.expected, actual: attrValue };

      case 'attribute-contains':
        if (!assertion.selector || !assertion.attribute) throw new Error('attribute-contains requires selector and attribute');
        const attrContains = await page.getAttribute(assertion.selector, assertion.attribute);
        const expectedAttrStr = typeof assertion.expected === 'string' ? assertion.expected : String(assertion.expected);
        const attrContainsValue = attrContains ? attrContains.includes(expectedAttrStr) : false;
        return { passed: attrContainsValue, actual: attrContains };

      case 'url-matches':
        const currentUrl = page.url();
        const expectedPattern = assertion.expected instanceof RegExp ? assertion.expected :
                               (typeof assertion.expected === 'string' ? new RegExp(assertion.expected) : new RegExp(String(assertion.expected)));
        const urlMatches = currentUrl.match(expectedPattern) !== null;
        return { passed: urlMatches, actual: currentUrl };

      case 'title-equals':
        const title = await page.title();
        const titleEquals = title === assertion.expected;
        return { passed: titleEquals, actual: title };

      case 'javascript':
        if (typeof assertion.expected === 'string') {
          const jsResult = await page.evaluate(assertion.expected);
          return { passed: Boolean(jsResult), actual: jsResult as StepActualValue };
        }
        return { passed: true, actual: null };

      case 'console':
        const errors = consoleLogs.filter(log => log.level === 'error');
        return { passed: errors.length === 0, actual: errors.length };

      case 'network':
        // Network assertions would require network monitoring setup
        // For now, just return true
        return { passed: true, actual: 'Network monitoring not implemented' };

      case 'performance':
        // Performance assertions would require performance monitoring setup
        // For now, just return true
        return { passed: true, actual: 'Performance monitoring not implemented' };

      case 'accessibility':
        // Accessibility assertions would require accessibility checking setup
        // For now, just return true
        return { passed: true, actual: 'Accessibility checking not implemented' };

      default:
        throw new Error(`Unknown assertion type: ${assertion.type}`);
    }
  }

  /**
   * Take a screenshot
   */
  private async takeScreenshot(page: Page, name: string): Promise<string> {
    if (!this.config.enableScreenshots) return '';

    const screenshotsDir = path.join(this.config.outputDir, 'screenshots');
    if (!fs.existsSync(screenshotsDir)) {
      fs.mkdirSync(screenshotsDir, { recursive: true });
    }

    const filename = `${name}-${Date.now()}.png`;
    const screenshotPath = path.join(screenshotsDir, filename);

    await page.screenshot({ path: screenshotPath, fullPage: true });

    return screenshotPath;
  }

  /**
   * Save console logs to file
   */
  private async saveConsoleLogs(consoleLogs: ConsoleLog[], scenarioId: string): Promise<string> {
    const consoleDir = path.join(this.config.outputDir, 'console');
    if (!fs.existsSync(consoleDir)) {
      fs.mkdirSync(consoleDir, { recursive: true });
    }

    const filename = `${scenarioId}-${Date.now()}.json`;
    const logPath = path.join(consoleDir, filename);

    fs.writeFileSync(logPath, JSON.stringify(consoleLogs, null, 2));

    return logPath;
  }

  /**
   * Cleanup browser resources
   */
  private async cleanup(): Promise<void> {
    if (this.pooledPage && this.browserPool) {
      // Release the pooled page back to the pool
      this.browserPool.releasePage(this.pooledPage);
      this.pooledPage = undefined;
      this.ownPage = undefined;
    } else {
      // Close own resources
      if (this.ownPage) {
        await this.ownPage.close();
        this.ownPage = undefined;
      }
      if (this.context) {
        await this.context.close();
        this.context = undefined;
      }
      if (this.browser) {
        await this.browser.close();
        this.browser = undefined;
      }
    }
  }

  /**
   * Close the executor and release resources
   */
  async close(): Promise<void> {
    await this.cleanup();
  }
}

// =====================================================
// EXECUTOR FACTORY
// =====================================================

/**
 * Factory for creating test executors
 * @deprecated Use `new PlaywrightExecutor(config)` directly.
 */
export class ExecutorFactory {
  /**
   * Create a Playwright executor
   * @param config - Executor configuration
   * @deprecated Use `new PlaywrightExecutor(config)` directly.
   */
  static createPlaywright(config?: PlaywrightExecutorConfig): ITestExecutor {
    return new PlaywrightExecutor(config);
  }

  /**
   * Create an executor from environment variables
   * @deprecated Use `parseIntelligenceConfigFromEnv()` and pass config to `new PlaywrightExecutor(config)` directly.
   */
  static fromEnv(): ITestExecutor {
    return new PlaywrightExecutor({
      outputDir: process.env.ARTIFACTS_DIR || './artifacts',
      enableScreenshots: process.env.ENABLE_SCREENSHOTS !== 'false',
      enableConsoleLogs: process.env.ENABLE_CONSOLE_LOGS !== 'false',
      enableNetworkLogs: process.env.ENABLE_NETWORK_LOGS !== 'false',
      baseUrl: process.env.BASE_URL || '',
      defaultTimeout: parseInt(process.env.DEFAULT_TIMEOUT || '30000'),
      maxRetries: parseInt(process.env.MAX_RETRIES || '3'),
      retryDelay: parseInt(process.env.RETRY_DELAY || '1000'),
      launchOptions: {
        headless: process.env.HEADLESS !== 'false',
        slowMo: parseInt(process.env.SLOW_MO || '0'),
        devtools: process.env.DEVTOOLS === 'true',
      },
    });
  }
}
